// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AcuantMobileSDK_iOS_Sample
{
	public partial class ShowResultViewController : UIViewController
	{
		public string ResultText { get; set; }

		public ShowResultViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			OutputLabel.Text = ResultText;
		}

		partial void CloseTapped(NSObject sender)
		{
			this.NavigationController.PopViewController(true);
		}
	}
}
