// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AcuantMobileSDK_iOS_Sample
{
	public partial class ShowResultViewController : UIViewController
	{
		public string ResultText
		{
			get { return OutputLabel.Text; }
			set { OutputLabel.Text = value; }
		}

		public ShowResultViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
